# Generated by Django 4.1.1 on 2022-09-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articles_abstract_alter_articles_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='abstract',
            field=models.TextField(),
        ),
    ]
