# Generated by Django 4.1.1 on 2022-09-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articles_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.TextField(),
        ),
    ]
