# Generated by Django 4.1.1 on 2022-09-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_articles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
