# Generated by Django 4.1.1 on 2022-09-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articles_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='url',
            new_name='article_url',
        ),
    ]
