# Generated by Django 4.1.1 on 2022-09-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_rename_url_articles_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_article_url',
            field=models.BooleanField(default=False),
        ),
    ]
