# Generated by Django 4.1.1 on 2022-09-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_note_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notes',
            name='note_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
