# Generated by Django 3.2.14 on 2022-08-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('title1', models.TextField()),
                ('title2', models.TextField()),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='about')),
                ('age', models.CharField(max_length=50)),
                ('clubhouse', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=50)),
            ],
        ),
    ]
