# Generated by Django 4.1.1 on 2022-09-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_detail',
            name='resume',
            field=models.FileField(blank=True, upload_to='about'),
        ),
    ]
