# Generated by Django 4.1.1 on 2022-09-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travelogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='Travelogue')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Travelogue')),
                ('travelogue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelogue.travelogue')),
            ],
        ),
    ]
