# Generated by Django 4.1.1 on 2022-09-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelogue',
            old_name='image',
            new_name='image_one',
        ),
        migrations.AddField(
            model_name='travelogue',
            name='image_two',
            field=models.ImageField(null=True, upload_to='Travelogue'),
        ),
    ]
